# Generated by Django 2.0.7 on 2018-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180704_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conment',
            name='blog',
        ),
        migrations.AddField(
            model_name='conment',
            name='source_id',
            field=models.CharField(default='1', max_length=25, verbose_name='文章id或source名称'),
        ),
        migrations.AddField(
            model_name='conment',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='conment',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog/%Y/%m', verbose_name='博客封面'),
        ),
        migrations.AlterField(
            model_name='conment',
            name='user',
            field=models.CharField(max_length=25, verbose_name='评论用户'),
        ),
    ]
