# Generated by Django 2.0.7 on 2018-07-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180704_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签名', 'verbose_name_plural': '标签名'},
        ),
    ]
