# Generated by Django 2.0.7 on 2018-07-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180704_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tagprofile',
        ),
    ]
